# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 3, 12, 3, 990876, tzinfo=utc), verbose_name='date published'),
        ),
    ]
