# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170321_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 9, 52, 15, 304117, tzinfo=utc), verbose_name='date published'),
        ),
    ]
