# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20170403_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 23, 29, 3, 915223, tzinfo=utc), verbose_name='date published'),
        ),
    ]
