# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20170404_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 0, 7, 42, 161082, tzinfo=utc), verbose_name='date published'),
        ),
    ]
